### PR TITLE
Add integration tests

### PR DESCRIPTION
**Pull request by BinrOp**
# Summary 

Those tests are designed to monitor the status of the marketstore for ticks data support:
- tick csv import
- writing and querying ticks with pymarketstore client
(+ some tests to check if latest docker image is runnable)

The status of those requirements are described in a README I added in this PR.

# Todo
- integrate those tests on ci ?

# Note

I am not sure of the right location to put this but wanted to share it here since I did it some time ago when I evaluated the support for ticks.

If it eases development or if it is helpful for new users as an example of using the marketstore with a simple architecture, then I'd be happy to make any changes to merge.

I can also quickly try to execute them in ci if requested (they run quite fast).

### CODE REVIEW

**Comment by BinrOp** [comment]
This is using the deprecated examples we can find here https://github.com/alpacahq/marketstore/tree/master/examples/deprecated

**Comment by BinrOp** [comment]
@umitanuki When you have some time, could you evaluate if this is relevant? If not, I will keep it on my personal repo in order to keep a trace.

**Comment by umitanuki** [comment]
Certainly. Let me take a look tomorrow.

**Comment by Notargets** [comment]
Hey Remy - I'm taking a look at this - hang tight!

**Comment by Notargets** [comment]
OK - so, two things:
1) I accidentally deleted your nice branch from under this PR (DOH!) - replaced it with the same content in a different branch - new PR as well
2) after figuring out the layout of Docker, etc now, there's a much simpler way to get these tests done IMO - I'm going to refactor now as an example...

**Comment by BinrOp** [comment]
Already looking better! :heart_eyes: : 

1. I'm not so confident with git myself but I think that maybe you deleted the branch locally since the remote on github seems unchanged? You should be able to pull locally the remote branch if you wanna keep it like this. Not sure how though...
However if it makes things easier for your development to work on https://github.com/alpacahq/marketstore/pull/117  Of course, feel free to close this PR!

2. Looking good! Please take it over! :laughing:

**Comment by BinrOp** [comment]
I have a small roadmap in mind if you don't mind me sharing:

# Roadmap

## Match previous version's features for ticks 
- fixing csv reader for importing tick data
- adapt pymarketstore client for reading the nanoseconds field added during importing ticks

This should port the current marketstore to previous version we used in terms of tick support.

## New tick features
For the future I'll let all of you draft it, as it might require some more fundamental changes?
One nice feature would be to emulate the tick csv reader with the python client so we can write ticks.

## Extend tests
Just fyi, as to make the behaviour transparent though it should not be considered a definitive requirement, I will add more tests for cases of:
- overwriting: consecutive writes in existing timeframes (when we update the data)
- unordered ticks within 1 timeframe or multiple timeframes

I'd love to have your feedback on this!

**Comment by Notargets** [comment]
:laughing: Should be able to simplify and also see what needs fixing for the new version...

**Comment by BinrOp** [comment]
Great! I am excited to see what you come up with!

**Comment by Notargets** [comment]
Ok - I want to leave this open to keep the open issues with ticks front/center until I can fix the broken client code, etc
The test contents have been merged with PR#117

**Comment by Notargets** [comment]
I merged #120 that fixed the CSV input for ticks, tick writes in general and now features the system tests to load the CSV data.

In the process, I see that the python client code has drifted so that it doesn't work with the latest marketstore - I'll be working on that a bit this weekend - hopefully it can be quickly fixed up!

**Comment by BinrOp** [comment]
Pheew great work! And fast! 
 
I'll have a look and update the tests once the python client is fixed, kudos :racehorse: !

**Pull request closed without merging**
