### PR TITLE
Add v4 version suffix to go module

### PR DESCRIPTION
**Pull request by leki75**
It is not possible to reference versions v2 and v3 if go versioning is not
handled properly. Eg. the `go get github.com/alpacahq/marketstore@v3.2.18`
raises an error.

```
go get github.com/alpacahq/marketstore@v3.2.18:
github.com/alpacahq/marketstore@v3.2.18: invalid version: module
contains a go.mod file, so major version must be compatible: should be
v0 or v1, not v3
```

See: https://blog.golang.org/v2-go-modules

### CODE REVIEW

**Comment by umitanuki** [comment]
Would it be just to add +compatible?

https://github.com/golang/go/wiki/Modules#can-a-module-consume-a-v2-package-that-has-not-opted-into-modules-what-does-incompatible-mean

**Comment by leki75** [comment]
> Would it be just to add +compatible?
> 
> https://github.com/golang/go/wiki/Modules#can-a-module-consume-a-v2-package-that-has-not-opted-into-modules-what-does-incompatible-mean

According to my experiments go will add `+incompatible` suffix if SemVer tagging is used but there is no `go.mod` file in the project directory. The `go.mod` file was added at ecc1946 commit until then the +incompatible versioning was working.
Now, referencing github.com/alpacahq/marketstore will get v2.3.8+incompatible version of marketstore which is the last version before `go.mod` was committed.

I am not a master of go modules and If you find an easier solution to get the latest master revision then we should use that method.

Anyway, sooner or later a proper versioning is needed and I think this is the right way unless you use go versions which are not aware of `GO111MODULE=on`. In this case creating a `v2` directory would be a better alternative.

**Comment by gnvk** [comment]
Using `+incompatible` no longer works for me:
```
github.com/alpacahq/marketstore@v3.2.18+incompatible: invalid version: +incompatible suffix not allowed: module contains a go.mod file, so semantic import versioning is required
```

**Comment by tibkiss** [comment]
@umitanuki/ @leki75  / @dakimura  / @gnvk  : I'd like to propose that we cut a v4.0.0 using this template as soon as the gRPC change is merged. WDYT?

**Pull request merged**
