### PR TITLE
Xignite feeder index symbols

### PR DESCRIPTION
**Pull request by dakimura**
An implementation for Xignite Feeder Plugin to store Index Symbols data (ex. TOPIX) retrieved from Xignite API

### CODE REVIEW

**Comment by Notargets** [comment]
Hey - can you please fix the merge conflicts here?

**Comment by dakimura** [comment]
@Notargets so sorry for my late response, I solved the conflict m(_ _;)m

**Comment by dakimura** [comment]
@Notargets please merge this when you are available!

**Comment by Notargets** [comment]
Done!

----
- Luke

**Pull request merged**
